[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# Fixed Version
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 200
# via_ir = true
ffi=true

# Local Testnet
# libraries = ['./libraries/Constants.sol:Constants:0x2e234DAe75C793f67A35089C9d99245E1C58470b', './libraries/DataTypes.sol:DataTypes:0xF62849F9A0B5Bf2913b396098F7c7019b51A820a', './libraries/Errors.sol:Errors:0x5991A2dF15A8F6A256D3Ec51E99254Cd3fb576A9', './libraries/Events.sol:Events:0xc7183455a4C133Ae270771860664b6B7ec320bB1']
# Goerli Testnet
libraries = ['./libraries/Constants.sol:Constants:0xc0f208cD760C472476A4Af93cf889aa79A70bb51', './libraries/DataTypes.sol:DataTypes:0xF2313a501B15Ee53a56a4A252864a7c7d53ced88', './libraries/Errors.sol:Errors:0x056a1258E952A5C9B85404C8cD77Fdea627D0362', './libraries/Events.sol:Events:0xA27939f95b4e8DC298B43ACaef4Fd4E7502FEE76']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
# Gas Report
gas_reports = ['KeyperModule', 'KeyperRoles', 'KeyperGuard']

# No match contracts
no_match_contract = 'Skip*'


[fmt]
# Maximum line length where formatter will try to wrap the line
line_length = 80
# Number of spaces per indentation level
tab_width = 4
# Print spaces between brackets
bracket_spacing = false
# Style of uint/int256 types
int_types = "long"
# If function parameters are multiline then always put the function attributes on separate lines
func_attrs_with_params_multiline = true
# Style of quotation marks
quote_style = "double"
# Style of underscores in number literals
number_underscore = "preserve"
